repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
    - id: mypy
      exclude: '(notebooks|tests)/.*'
      args: [--strict, --ignore-missing-imports]
      additional_dependencies:
          - 'numpy'
          - 'flask'
          - 'pandas'
          - 'transformers'
          - 'mlflow'
          - 'tqdm'
          - 'pyyaml'
- repo: https://github.com/jendrikseipp/vulture
  rev: 'v2.3'  # or any later Vulture version
  hooks:
    - id: vulture
      args: [ "src/tests/" ]
- repo: https://github.com/yunojuno/pre-commit-xenon
  rev: cc59b0431a5d072786b59430e9b342b2881064f6
  hooks:
  - id: xenon
    args: ["--max-average=A", "--max-modules=B", "--max-absolute=B"]